name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
title: "[Feature]: "
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What do you propose as a solution?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
