name: Link Checker

on:
  schedule:
    - cron: '30 2 * * 1' # Weekly, Mondays 02:30 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  link-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --max-concurrency 8 --accept 200,206,429 --exclude-mail README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
