name: Update README

on:
  schedule:
    - cron: '0 */3 * * *' # every 3 hours
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10
    concurrency:
      group: update-readme
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v5
      - name: Update GitHub Activity
        uses: TheDanniCraft/activity-log@v0.0.9
        with:
          GITHUB_USERNAME: "mohammedfirdouss"
          GITHUB_TOKEN: ${{ secrets.ACTIVITY_PAT }}
          EVENT_LIMIT: "5"
          OUTPUT_STYLE: "MARKDOWN"
          README_PATH: "README.md"
          COMMIT_MESSAGE: "chore(readme): update recent activity"
          HIDE_DETAILS_ON_PRIVATE_REPOS: "true"
          IGNORE_EVENTS: "PushEvent"
